language: node_js
sudo: required
addons:
  chrome: stable
node_js:
  - stable
  - "8"
branches:
  only: master
before_script:
  - npm install -g @angular/cli@6.0.8
  - npm link
after_failure:
  - cat /home/travis/build/MSakamaki/-monaca-schematics/npm-debug.log
notifications:
  slack: gxp:ov6kUHOOChvUDSgHMCLnUiuu
script:
  - npm run test.all
cache:
  directories: node_modules