# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

install:
  # Update Node.js
  # 標準で入っている Node.js を更新します (2014/11/13 時点では、v0.10.32 が標準)
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - node --version

  # Update NPM
  - npm install -g npm
  - npm --version

  # Update node-gyp
  - npm install -g node-gyp

  # global install
  - npm install -g @angular/cli@6.0.0-beta.8
  - npm install -g @angular-devkit/schematics-cli@0.4.8
  - npm install -g del-cli

  # npm install
  - npm install

test_script:
# テスト用のコマンドを指定します
  - npm test

environment:
  matrix:
    - nodejs_version: 8

init:
  - git config --global core.autocrlf false

branches:
  only:
    - master

build: off
deploy: off