# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
image:
  - Visual Studio 2017
install:
  # set typescript
  # https://www.appveyor.com/docs/build-environment/#typescript
  - set path=%programfiles(x86)%\\Microsoft SDKs\TypeScript\2.6;%path%
  # Update Node.js
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - node --version

  # Update NPM
  - npm install -g npm
  - npm --version

  # Update node-gyp
  - npm install -g node-gyp

  # global install
  - npm install -g @angular/cli@6.0.0-rc.2
  - npm install -g @angular-devkit/schematics-cli@0.5.4
  - npm install -g del-cli

  # npm install

  - npm install
  - npm install @angular/cli@6.0.0-rc.2
  # global install
  - npm link

test_script:
# テスト用のコマンドを指定します
  - npm run test
  - npm run e2e

environment:
  matrix:
    - nodejs_version: 8
    - nodejs_version: 9

init:
  - git config --global core.autocrlf false

branches:
  only:
    - master

build: off
deploy: off