# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
image:
  - Visual Studio 2017
install:
  # set typescript
  # https://www.appveyor.com/docs/build-environment/#typescript
  - set path=%programfiles(x86)%\\Microsoft SDKs\TypeScript\2.6;%path%
  # Update Node.js
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - node --version

  # Update NPM
  - npm install -g npm
  - npm --version

  # Update node-gyp
  - npm install -g node-gyp

  # global install
  - npm install -g @angular/cli@next
  - npm install -g @angular-devkit/schematics-cli@latest

  # npm install
  - npm install

  # link
  - npm link

test_script:
  - npm run test
  - mkdir tmp
  - cd tmp
  - ng new myapp -c @monaca/schematics
  - cd myapp
  - ng lint
  - ng build
  - ng test --browsers ChromeHeadless

environment:
  matrix:
    - nodejs_version: 8
    - nodejs_version: 9

init:
  - git config --global core.autocrlf false

branches:
  only:
    - master

build: off
deploy: off